### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by Zumochi** [DomiStyle/docker-eldewrito#10]
How should I debug not being able to connect to the game server?

Funnily enough I can connect to the rcon port and send commands. I just can't connect otherwise.

Startup log: https://gist.github.com/Zumochi/324f0c7a66469022f7b2c673e774dcd3

Trying latest tag, as well as building the image myself.

**Comment by Alenux55** [comment]
How are you trying to connect to the game server? Are you trying to find it in the master server list, or are you using "Server.connect [server_ip] [password (if there is one)]"?

**Comment by Zumochi** [comment]
@Alenux55 the latter. I will have to re-try with the latest image 😃

**Comment by Alenux55** [comment]
Yeah, give the latest version a try. With the old one, were you able to see all the server information if you opened a browser and went to [server_ip]:11775?
