### ISSUE TITLE
Is this 32-bit?

### ISSUE THREAD

**Issue by Engineer-of-Stuff** [DomiStyle/docker-eldewrito#14]
When I start the server it endlessly restarts and the log is filled with this error:
`eldewrito_1  | standard_init_linux.go:178: exec user process caused "exec format                                                                                                  error"`

I believe that this is caused by my 32-bit (i686) server not being able to run this 64-bit program.
I do have wine installed.

Is Eldewrito server 32-bit?

**Comment by DomiStyle** [comment]
The image is based on the 64-bit Ubuntu image so you won't be able to use it on 32-bit without rebuilding yourself.

**Comment by Engineer-of-Stuff** [comment]
How would I do that?

**Comment by DomiStyle** [comment]
You would have to adjust the [Dockerfile](https://github.com/DomiStyle/docker-eldewrito/blob/master/Dockerfile) and provide a base image of Ubuntu that works on 32-bit. You would also need to modify the installation of wine to work on 32-bit machines.

Is there a particular reason you need a 32-bit version?

**Comment by Engineer-of-Stuff** [comment]
My server is 32-bit (yes, I know it's time to upgrade).

32-bit Wine is installed by default, so it works fine right now. 

What do I modify in the Dockerfile? This might be outside of my ability.

**Comment by 09eragera09** [comment]
I'd like to know as well, my VPS is arm-based, not x86_64

**Comment by DomiStyle** [comment]
@09eragera09 Yes, this image is x86_64. You can build the image for ARM but wine won't be able to run Eldewrito without an emulator.
