### ISSUE TITLE
Using with Pterodactyl

### ISSUE THREAD

**Issue by macaws** [DomiStyle/docker-eldewrito#18]
Since Pterodactyl (pterodactyl.io) uses Docker I thought this would be easy to import over but I'm not having much luck. 

I know this mod is pretty much abandoned at this point but I did want to try this.

**Comment by DomiStyle** [comment]
I haven't really looked at Pterodactyl for a while but I will give it a try when I can.

**Comment by macaws** [comment]
If you need a working server to test on DM me

**Comment by DomiStyle** [comment]
See here: https://github.com/proferabg/eldewrito-pterodactyl
