### ISSUE TITLE
Failing to start server

### ISSUE THREAD

**Issue by encounter** [DomiStyle/docker-eldewrito#2]
Currently getting the following lines looping in the log:

```
eldewrito_1  | Initializing
eldewrito_1  | Cleaning up
eldewrito_1  | Starting virtual frame buffer
eldewrito_1  | Starting dedicated server
eldewrito_1  | 000b:fixme:winediag:start_process Wine Staging 3.6 is a testing version containing experimental patches.
eldewrito_1  | 000b:fixme:winediag:start_process Please mention your exact version when filing bug reports on winehq.org.
eldewrito_1  | 0009:fixme:d3d:wined3d_guess_card No card selector available for card vendor 0000 (using GL_RENDERER "llvmpipe (LLVM 5.0, 256 bits)").
eldewrito_1  | 0009:err:d3d:wined3d_adapter_find_polyoffset_scale PolygonOffset scale factor detection failed, using fallback value 2^23.
eldewrito_1  | 0009:fixme:ole:CoInitializeSecurity ((nil),-1,(nil),(nil),0,3,(nil),0,(nil)) - stub!
eldewrito_1  | 0009:fixme:wbemprox:client_security_SetBlanket 0xf0dd882c, 0x1446d0, 10, 0, (null), 3, 3, (nil), 0x00000000
eldewrito_1  | 0009:fixme:wbemprox:client_security_Release 0xf0dd882c
eldewrito_1  | 0009:fixme:wbemprox:enum_class_object_Next timeout not supported
eldewrito_1  | 0009:fixme:d3d:wined3d_guess_card No card selector available for card vendor 0000 (using GL_RENDERER "llvmpipe (LLVM 5.0, 256 bits)").
eldewrito_1  | 0009:err:d3d:wined3d_adapter_find_polyoffset_scale PolygonOffset scale factor detection failed, using fallback value 2^23.
eldewrito_1  | 0009:fixme:d3d:wined3d_guess_card No card selector available for card vendor 0000 (using GL_RENDERER "llvmpipe (LLVM 5.0, 256 bits)").
eldewrito_1  | 0009:err:d3d:wined3d_adapter_find_polyoffset_scale PolygonOffset scale factor detection failed, using fallback value 2^23.
```

This is running on a VPS, so there's no graphics card available. I assumed that headless would work anyway.

CentOS 7.4, docker container version 0.6-test5

**Comment by DomiStyle** [comment]
Headless is working, I'm running multiple instances inside a VM without GPU. What Docker version are you using?

**Comment by encounter** [comment]
`Docker version 17.05.0-ce, build 89658be`

**Comment by DomiStyle** [comment]
Not entirely related since your log differs but can you give this a try? https://github.com/DomiStyle/docker-eldewrito/issues/1#issuecomment-384256589

Other than that, here's what a successful launch looks like: https://github.com/DomiStyle/docker-eldewrito/issues/1#issuecomment-383837801

I followed my tutorial [here](https://github.com/DomiStyle/docker-eldewrito#tutorial-for-ubuntu-hosts) and everything worked out of the box, I wasn't able to recreate your issue.

**Comment by encounter** [comment]
Tried it out on my Arch Linux workstation (Docker 18.04), which led me to realize I was using the wrong game files. Dumb mistake.

Now with the correct game files, everything is working fine on both my workstation and the VPS. Files are in `/opt/eldewrito/{game,config,logs}` and owned by root.

As an aside, would love to have the game server _not_ run as root (even within the container), which I've seen you mention before.

Thanks a lot for your work!

**Comment by DomiStyle** [comment]
> As an aside, would love to have the game server not run as root (even within the container), which I've seen you mention before.

Me too. This was just to get the image up and running faster. Once most issues are solved I will move over to doing just that.
