### ISSUE TITLE
Cant build Docker image.

### ISSUE THREAD

**Issue by Just-Weeb** [DomiStyle/docker-eldewrito#21]
I was trying to build the docker image to eventually make some tweaks to the start script. I tried forking the repo and making a docker hub repo, and also tried doing docker build githuburl and both had the same error when trying to build an image. Any clue what could be causing this? My machine has Ubuntu 18.04
```
The following packages have unmet dependencies:
winehq-stable : Depends: wine-stable (= 5.0.0~bionic)
[91mE: Unable to correct problems, you have held broken packages
```

**Comment by DomiStyle** [comment]
Wine 5 [added a dependency for FAudio](https://forum.winehq.org/viewtopic.php?f=8&t=32192) and Ubuntu 18.04 doesn't have a package for it.

I added [a fix](https://github.com/DomiStyle/docker-eldewrito/commit/fa4db24abcf2a3988fba2ae0682dd1b544662fdd) for it but I can't test if the dedicated server itself still runs with Wine 5, maybe you can give it a try?

**Comment by Just-Weeb** [comment]
Thanks for the fix. It works perfectly, I got Dedicated server is running with Wine 5, so all is good.   I had tried adding an FAudio fix, but it was different than the one you used, so that's probably why I still couldn't get it to build.
