### ISSUE TITLE
Best way to use for multiple instances?

### ISSUE THREAD

**Issue by timelf123** [DomiStyle/docker-eldewrito#5]

**Comment by DomiStyle** [comment]
Right now you have to change all the ports in your docker-compose file to a different port, like this:

    ports:
        - 11778:11778/udp
        - 11779:11779/tcp
        - 11780:11780/tcp
        - 11781:11781/tcp

After that you need to change all your ports in your dewrito_prefs.cfg. I would like to fix this but currently ElDewrito doesn't support anything else.

You can also add a second instance to your docker-compose like this:

    version: '2'

    services:
    srv1:
        image: domistyle/eldewrito
        restart: always
        ports:
        - 11774:11774/udp
        - 11775:11775/tcp
        - 11776:11776/tcp
        - 11777:11777/tcp
        volumes:
        - /path/to/game:/game
        - /path/to/config:/config
        - /path/to/logs:/logs
        cap_add:
        - SYS_PTRACE
    srv2:
        image: domistyle/eldewrito
        restart: always
        ports:
        - 11778:11778/udp
        - 11779:11779/tcp
        - 11780:11780/tcp
        - 11781:11781/tcp
        volumes:
        - /path/to/game:/game
        - /path/to/config:/config
        - /path/to/logs:/logs
        cap_add:
        - SYS_PTRACE

I will see if I can workaround that by using the -instance switch somehow. Not sure if I can get the hang of a ElDewrito developer right now to change something.

**Comment by wallopthecat** [comment]
To avoid duped game folders, I plan on solving by mounting the prefs file separately. In theory this should work
```
- /path/to/game:/game
- /path/to/game/dewrito_prefs.cfg:/game/dewrito_prefs.cfg
- /path/to/configsrv1:/config
```

**Comment by DomiStyle** [comment]
Yes, that would work. Not the most elegant solution but it works for now.

**Comment by wallopthecat** [comment]
No luck with that hack. Are you just duping the game folder for each instance?


`"/var/lib/docker/aufs/mnt/97129a2e822f602af7cde432710ef6ebae3dcdfa4e8a34d4cc10c8b0de6a1b00/game/dewrito_prefs.cfg\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type`

**Comment by DomiStyle** [comment]
@wallopthecat I'm going to implement a workaround for this in the next image. Until then just keep multiple game folders.

**Comment by DomiStyle** [comment]
@wallopthecat Image was just updated. You can now define an alphanumeric identifier as INSTANCE_ID. It will use the configuration from /config/dewrito_prefs.cfg.

More details here: https://github.com/DomiStyle/docker-eldewrito/releases/tag/0.6-test6

**Comment by wallopthecat** [comment]
@DomiStyle thanks for your work, you are a great asset!

**Comment by Alenux55** [comment]
Awesome work, set up a couple servers tonight and it was easy!
