### ISSUE TITLE
Can't use rcon or voip.

### ISSUE THREAD

**Issue by pkillboredom** [DomiStyle/docker-eldewrito#6]
Hi, I cannot seem to use rcon or voip. The ports appear to be closed externally, but all signs indicate they're open. i.e.
```
luke@HaloDrop1:~/edserver$ sudo lsof -i
COMMAND    PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
docker-pr 1834 root    4u  IPv6  17303      0t0  TCP *:11777 (LISTEN)
docker-pr 1856 root    4u  IPv6  18036      0t0  TCP *:11776 (LISTEN)
docker-pr 1868 root    4u  IPv6  18063      0t0  TCP *:11775 (LISTEN)
docker-pr 1880 root    4u  IPv6  18108      0t0  UDP *:11774
````

But externally that looks like this:
```
PS C:\Users\Luke> test-netconnection -port 11776 -computername ed.pkillboredom.com -informationlevel detailed
WARNING: TCP connect to (167.99.12.248 : 11776) failed


ComputerName            : ed.pkillboredom.com
RemoteAddress           : 167.99.12.248
RemotePort              : 11776
NameResolutionResults   : 167.99.12.248
MatchingIPsecRules      :
NetworkIsolationContext : Internet
IsAdmin                 : False
InterfaceAlias          : Ethernet 4
SourceAddress           : 192.168.1.126
NetRoute (NextHop)      : 192.168.1.1
PingSucceeded           : True
PingReplyDetails (RTT)  : 23 ms
TcpTestSucceeded        : False
```

I can connect to the game and the json server works, but rcon and voice are unavailable,

**Comment by Missiongames** [comment]
I have the same issue with my server when connecting externally.

```
PS C:\Users\xxxx> test-netconnection -port 11776 -computername greenswe.de -informationlevel detailed
WARNING: TCP connect to (167.99.85.178 : 11776) failed


ComputerName            : greenswe.de
RemoteAddress           : 167.99.85.178
RemotePort              : 11776
NameResolutionResults   : 167.99.85.178
MatchingIPsecRules      :
NetworkIsolationContext : Internet
IsAdmin                 : False
InterfaceAlias          : Ethernet
SourceAddress           : 192.168.0.2
NetRoute (NextHop)      : 192.168.0.1
PingSucceeded           : True
PingReplyDetails (RTT)  : 38 ms
TcpTestSucceeded        : False
```

Do you also use DigitalOcean as host? Noticed that our IP addresses are fairly identical. Beginning to wonder if this is a host configuration issue.

**Comment by pkillboredom** [comment]
Yeah I use DigitalOcean, NYC1. Maybe I'll try switching ports, but I have to sleep now, real tired.

**Comment by Missiongames** [comment]
Alright, that is interesting then. I have sent a ticket to DigitalOcean already about this issue, in case they know what's going on on their side.

**Comment by timelf123** [comment]
Does your host have UFW or another firewall enabled?

**Comment by DomiStyle** [comment]
Try running ```wget -v http://127.0.0.1:11776``` on your DigitalOcean host.

A correct response looks like this:

    domi@test01:~$ wget -v http://127.0.0.1:11776
    --2018-04-25 19:25:31--  http://127.0.0.1:11776/
    Connecting to 127.0.0.1:11776... connected.
    HTTP request sent, awaiting response... 426 Upgrade Required
    2018-04-25 19:25:31 ERROR 426: Upgrade Required.

That means there's a network/firewall issue.

**Comment by pkillboredom** [comment]
Tried a different port, still not working. Also waiting on a response from digitalocean.

**Comment by pkillboredom** [comment]
I made a new droplet on debian and manually installed docker, works perfectly OOTB. You may wish to consider warning users that the pre-made Ubuntu/Docker image from DigitalOcean does not work. Closing for now.
