### ISSUE TITLE
Connection Refused

### ISSUE THREAD

**Issue by santasia** [DomiStyle/docker-eldewrito#7]
Started up a fresh install of Ubuntu 16.04 and followed the tutorial to the letter. But when the time comes to check if it works in a browser I get the error "ERR_CONNECTION_REFUSED". And when I try to connect on Halo Online via console I get the error "Unable to connect to server. (error: 12029/0)". Apologies for posting on most likely an easy to fix issue, I've just never used Docker before and anytime I search up similar threads it doesn't seem to help. Here's what my "docker-compose logs" reads:

eldewrito_1  | Initializing
eldewrito_1  | Could not find an existing dewrito_prefs.cfg. Using default.
eldewrito_1  | Make sure to adjust important settings like your RCon password!
eldewrito_1  | Copying default veto/voting json.
eldewrito_1  | Cleaning up
eldewrito_1  | Starting virtual frame buffer
eldewrito_1  | Starting dedicated server
eldewrito_1  | 000b:fixme:winediag:start_process Wine Staging 3.6 is a testing version containing experimental patches.
eldewrito_1  | 000b:fixme:winediag:start_process Please mention your exact version when filing bug reports on winehq.org.
eldewrito_1  | 0009:fixme:kerberos:kerberos_SpInstanceInit 65536,0x7da5c3a0,(nil): stub
eldewrito_1  | Initializing
eldewrito_1  | Cleaning up
eldewrito_1  | Starting virtual frame buffer
eldewrito_1  | Starting dedicated server
eldewrito_1  | 000b:fixme:winediag:start_process Wine Staging 3.6 is a testing version containing experimental patches.
eldewrito_1  | 000b:fixme:winediag:start_process Please mention your exact version when filing bug reports on winehq.org.
eldewrito_1  | 0009:fixme:kerberos:kerberos_SpInstanceInit 65536,0x7da1c3a0,(nil): stub
eldewrito_1  | Initializing
eldewrito_1  | Cleaning up
eldewrito_1  | Starting virtual frame buffer
eldewrito_1  | Starting dedicated server
eldewrito_1  | 000b:fixme:winediag:start_process Wine Staging 3.6 is a testing version containing experimental patches.
eldewrito_1  | 000b:fixme:winediag:start_process Please mention your exact version when filing bug reports on winehq.org.
eldewrito_1  | 0009:fixme:kerberos:kerberos_SpInstanceInit 65536,0x7da5c3a0,(nil): stub

Any help on the issue would be great! Would love to start getting some Halo: Online dedicated servers running and sadly Windows Servers are pretty expensive.

**Comment by DomiStyle** [comment]
Take a look at this: https://github.com/DomiStyle/docker-eldewrito/issues/1#issuecomment-384256589

This will be fixed in the next image release but that way you can get it running in the mean time.

**Comment by santasia** [comment]
Oh awesome, that worked perfectly. Yeah when you said it had to be ran in root I thought I could get by that with sudo privs, guess not. Thanks!
