### ISSUE TITLE
64-bit Wine Support/Exec Format Error

### ISSUE THREAD

**Issue by Step7750** [DomiStyle/docker-eldewrito#8]
I've attempted to install this docker and from what I've seen, it is force installing a 32-bit version of wine that causes a `/start.sh: line36: cannot execute binary file: Exec format error` when launching.

Host system is running on Unraid 6.1.9.

**Comment by DomiStyle** [comment]
Wine is always installing some 32-bit binaries, hence why you need to add the architecture before you can even install Wine from their repository.

However, 32-bit runs just fine on 64-bit hardware so I don't see how that would cause this error message. Everyone is running this on 64-bit hardware after all.

A different suggestion: Can you make sure the eldorado.exe is mounted in /game and it's the correct one?

**Comment by Step7750** [comment]
Thanks for the reply!

I've looked into this a bit further, and it seems to be an incompatibility with Unraid's Docker implementation. I've decided to spin up a VM instead to avoid these issues.

While this probably doesn't affect many other people, I believe that you could make it install 64-bit wine along with the 32bit libraries to mitigate these issues (but it apparently is more unstable).
